Fix exit code handeling

diff --git a/.github/workflows/consumer_test.yml b/.github/workflows/consumer_test.yml
--- a/.github/workflows/consumer_test.yml
+++ b/.github/workflows/consumer_test.yml
@@ -44,17 +44,27 @@ jobs:
       - name: Run Consumer tests
 
         run: |
-          .venv_docs/bin/python -m pytest -s -vv src/tests/ --repo="$CONSUMER" --junitxml="reports/${{ matrix.consumer }}.xml" 
+          .venv_docs/bin/python -m pytest -vv src/tests/ \
+          --repo="$CONSUMER" \
+          --junitxml="reports/${{ matrix.consumer }}.xml"
+          pytest_rc=$?
+
           if [ -f "consumer_test.log" ]; then
-            mv "consumer_test.log" "reports/${{ matrix.consumer }}.log"
-          elif [ -f "reports/rich.log" ]; then
-            mv "reports/consumer_test.log" "reports/${{ matrix.consumer }}.log"
+            src_log="consumer_test.log"
+          elif [ -f "reports/consumer_test.log" ]; then
+            src_log="reports/consumer_test.log"
           else
-            echo "conumser_test.log not found; expected at ./consumer_test.log or ./reports/consumer_test.log"
-            exit 1
+            echo "consumer_test.log not found; expected at ./consumer_test.log or ./reports/consumer_test.log"
+          exit ${pytest_rc:-1}
           fi
-          echo "=== Tail 12 lines: $out_log ==="
-          tail -n 12 "reports/${{ matrix.consumer }}.log" || true
+
+          dest_log="reports/${{ matrix.consumer }}.log"
+          mv "$src_log" "$dest_log"
+
+          echo "=== Tail 12 lines: $dest_log ==="
+          tail -n 12 "$dest_log" || true
+
+          exit $pytest_rc
         env:
           FORCE_COLOR: "1"
           TERM: xterm-256color
